version: "{build}"

cache:
 - C:\Cache
 - C:\gopath/pkg/mod -> go.sum

clone_folder: C:\gopath\src\github.com\influxdata\telegraf

environment:
  GOPATH: C:\gopath
  GO111MODULE: 'on'

platform: x64

install:
  - IF NOT EXIST "C:\Cache" mkdir C:\Cache
  - IF NOT EXIST "C:\Cache\go1.12.5.msi" curl -o "C:\Cache\go1.12.5.msi" https://storage.googleapis.com/golang/go1.12.5.windows-amd64.msi
  - IF EXIST "C:\Go" rmdir /S /Q C:\Go
  - msiexec.exe /i "C:\Cache\go1.12.5.msi" /quiet
  - choco install make
  - cd "%GOPATH%\src\github.com\influxdata\telegraf"
  - git config --system core.longpaths true
  - go version
  - go env

build_script:
  - make

test_script:
  - make check
  - make test-windows

artifacts:
  - path: telegraf.exe
